# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Matrizes Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    # Compilar main
    - name: Compilar Main
      run: javac src/NumAleatorios.java

    # Executar main
    - name: Executar Main
      run: java src/NumAleatorios.java

    - name: Extract version from tag
      id: vars
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        # Name of the Docker image
        image: vigamy/java_console
        tags: |
          vigamy/java_console:${{ env.VERSION }}
          vigamy/java_console:latest
        # Tags override for Docker image
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
