# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Matrizes Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    # Compilar main
    - name: Compilar Main
      run: javac src/NumAleatorios.java

    # Executar main
    - name: Executar Main
      run: java src/NumAleatorios.java

    # Versinamento
    - name: Git Version
    # You may pin to the exact commit or the version.
    # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
      uses: codacy/git-version@2.4.0
      with:
        # The name of the release branch
        release-branch: main
        # The name of the dev branch
        dev-branch: main
          

    # Dar push da imagem
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        # Name of the Docker image
        image: vigamy/java_console
        # Tags override for Docker image
        registry: docker.io
        tags: ${{ github.run_number }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
